export enum RequestType {
  CONNECT,
  DISCONNECT,
  GETCONNECTEDPLAYERS,
  SETUSERNAME,
  USERNAMEEXIST,
  GETPLAYERS,
  SENDPLAYERS,
  CHANGEPOSITION,
  CHANGEROTATION,
  SENDPOSITION,
  SENDROTATION,
  KILLPLAYER,
  ADDBULLET,
  UPDATEHEAL
}
